services:
  postgres:
    image: postgres:16-alpine
    container_name: tcg_postgres
    environment:
      POSTGRES_USER: tcg_user
      POSTGRES_PASSWORD: tcg_password
      POSTGRES_DB: tcg_matchmaking
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
